name: pre-commit checks

on:
  workflow_dispatch:
  workflow_call:

jobs:
  run_precommit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.3"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit cpplint

      - name: Precommit checks
        run: |
          pre-commit install
          pre-commit run -a